'use client';

import React, { useState, useCallback } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db, type DocumentItem } from '@/db/database';
import { useDocumentStore } from '@/store/useDocumentStore';
import Card from '@/components/ui/Card';
import {
  FileText, Upload, CheckCircle, AlertTriangle, User,
  Calendar, Sparkles, Trash2, HardDrive, Download,
  FileDown, FileCode, ArrowRight, Loader2, X, FolderOpen
} from 'lucide-react';

interface ExtractedData {
  summary: string;
  tasks: string[];
  deadlines: string[];
  opportunities: string[];
  risks: string[];
  contacts: string[];
}

// --- Export helpers ---
function exportAsText(fileName: string, data: ExtractedData) {
  const lines = [
    `KGOS Document Intelligence Export`,
    `Source File: ${fileName}`,
    `Exported: ${new Date().toLocaleString('en-IN')}`,
    `${'─'.repeat(60)}`,
    ``,
    `EXECUTIVE SUMMARY`,
    data.summary,
    ``,
    `TASKS`,
    ...data.tasks.map((t, i) => `  ${i + 1}. ${t}`),
    ``,
    `DEADLINES`,
    ...data.deadlines.map((d, i) => `  ${i + 1}. ${d}`),
    ``,
    `OPPORTUNITIES`,
    ...data.opportunities.map((o, i) => `  ${i + 1}. ${o}`),
    ``,
    `RISKS`,
    ...data.risks.map((r, i) => `  ${i + 1}. ${r}`),
    ``,
    `CONTACTS`,
    ...data.contacts.map((c, i) => `  ${i + 1}. ${c}`),
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  triggerDownload(blob, `${sanitizeFileName(fileName)}_kgos_export.txt`);
}

function exportAsHTML(fileName: string, data: ExtractedData) {
  const section = (title: string, items: string[], color: string) =>
    items.length === 0 ? '' : `
      <section style="margin-bottom:24px">
        <h2 style="font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:${color};margin:0 0 10px">${title}</h2>
        <ul style="margin:0;padding-left:20px;color:#d4d4d8;font-size:13px;line-height:1.7">
          ${items.map(i => `<li>${i}</li>`).join('')}
        </ul>
      </section>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>KGOS Intelligence Report — ${fileName}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: #09090b; color: #d4d4d8; font-family: 'Inter', system-ui, sans-serif; padding: 40px; }
    header { border-bottom: 1px solid #27272a; padding-bottom: 20px; margin-bottom: 28px; }
    h1 { font-size: 20px; font-weight: 800; color: #f4f4f5; }
    .meta { font-size: 12px; color: #71717a; margin-top: 6px; }
    .summary { background: #18181b; border: 1px solid #27272a; border-radius: 10px; padding: 16px; font-size: 13px; line-height: 1.7; color: #a1a1aa; margin-bottom: 24px; }
    footer { margin-top: 40px; font-size: 11px; color: #3f3f46; border-top: 1px solid #1c1c1e; padding-top: 16px; }
  </style>
</head>
<body>
  <header>
    <h1>📄 KGOS Intelligence Report</h1>
    <div class="meta">Source: ${fileName} &nbsp;·&nbsp; Generated: ${new Date().toLocaleString('en-IN')} &nbsp;·&nbsp; Kumar Gourav Operating System</div>
  </header>
  <section style="margin-bottom:24px">
    <h2 style="font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:0.08em;color:#3b82f6;margin:0 0 10px">Executive Summary</h2>
    <p class="summary">${data.summary}</p>
  </section>
  ${section('Action Items', data.tasks, '#10b981')}
  ${section('Deadlines', data.deadlines, '#f59e0b')}
  ${section('Opportunities', data.opportunities, '#22d3ee')}
  ${section('Risk Signals', data.risks, '#f43f5e')}
  ${section('Contacts', data.contacts, '#a855f7')}
  <footer>Generated by KGOS 2031 Document Intelligence Center</footer>
</body>
</html>`;
  const blob = new Blob([html], { type: 'text/html' });
  triggerDownload(blob, `${sanitizeFileName(fileName)}_kgos_report.html`);
}

function exportAsJSON(fileName: string, data: ExtractedData) {
  const payload = {
    metadata: {
      source: fileName,
      generatedAt: new Date().toISOString(),
      system: 'KGOS 2031',
    },
    intelligence: data,
  };
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  triggerDownload(blob, `${sanitizeFileName(fileName)}_kgos_data.json`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function sanitizeFileName(name: string) {
  return name.replace(/[^a-z0-9]/gi, '_').toLowerCase().replace(/_+/g, '_');
}

// --- Mock extraction library ---
const MOCK_EXTRACTIONS: Record<string, ExtractedData> = {
  default: {
    summary: 'Formulation specification sheet outlining viscosity metrics and trial batch conditions for Carrageenan blend stabilizer systems for Heritage Foods dairy applications.',
    tasks: [
      'Prepare 500g prototype blend (Ratio 70:30 Kappa to Locust Bean Gum)',
      'Log gel strength and syneresis metrics after 24h refrigeration',
      'Submit trial batch results to client portal',
    ],
    deadlines: ['Submit trial feedback to Heritage Foods by June 28, 2026'],
    opportunities: ['Substitute imported pectin with custom Carrageenan blend — margin uplift ~12%'],
    risks: ['High moisture in seaweed feedstock may degrade gel strength by 8–15%'],
    contacts: ['Dr. Ramesh Kumar (R&D Director) — ramesh.k@heritage.com'],
  },
  po: {
    summary: 'Purchase order from Kwality Dairy for 200 kg monthly supply of KAFS Kappa Carrageenan Blend KC-32. Payment terms: Net 30, delivery by 1st of each month.',
    tasks: [
      'Confirm production capacity for 200 kg monthly volume',
      'Update ERP inventory requirement for KC-32 raw materials',
      'Raise invoice after first delivery confirmation',
    ],
    deadlines: ['First delivery due: July 1, 2026', 'Invoice submission: July 5, 2026'],
    opportunities: ['Upsell complementary locust bean gum blend at 5% discount on combined order'],
    risks: ['Single-source supply dependency risk if seaweed raw material shortage occurs in Q3'],
    contacts: ['Rajesh Sharma (Procurement Head) — rajesh.s@kwality.com', '+91 98765 43210'],
  },
  exam: {
    summary: 'FSSAI Food Analyst recruitment notification 2026. 42 vacancies across Regional Offices. Eligibility: M.Sc. / M.Tech in Food Technology. Age limit 32. Application window: July 1–31, 2026.',
    tasks: [
      'Download and complete FSSAI online application form before July 31',
      'Arrange attested copies of degree certificates and experience letter',
      'Prepare for Food Safety Regulations and Microbiology sections (highest weightage)',
    ],
    deadlines: ['Application deadline: July 31, 2026', 'Admit card expected: August 15, 2026'],
    opportunities: ['42 vacancies — highest in 4 years. Strong eligibility profile. Apply immediately.'],
    risks: ['Preparation lag in Food Laws chapter (currently at 68% mock score vs 80% target)'],
    contacts: ['FSSAI Regional Director, Mumbai — recruitment@fssai.gov.in'],
  },
};

function detectExtractionType(fileName: string): ExtractedData {
  const lower = fileName.toLowerCase();
  if (lower.includes('po') || lower.includes('purchase') || lower.includes('order')) return MOCK_EXTRACTIONS.po;
  if (lower.includes('exam') || lower.includes('fssai') || lower.includes('notification') || lower.includes('vacancy')) return MOCK_EXTRACTIONS.exam;
  return MOCK_EXTRACTIONS.default;
}

// Drag-and-drop zone component
function DropZone({ onFile }: { onFile: (f: File) => void }) {
  const [isDragging, setIsDragging] = useState(false);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files?.[0];
    if (file) onFile(file);
  }, [onFile]);

  return (
    <div
      onDrop={handleDrop}
      onDragOver={e => { e.preventDefault(); setIsDragging(true); }}
      onDragLeave={() => setIsDragging(false)}
      className={`flex flex-col items-center justify-center border-2 border-dashed rounded-xl p-10 transition-all cursor-default ${
        isDragging
          ? 'border-blue-500 bg-blue-500/5'
          : 'border-zinc-800 bg-zinc-950/20 hover:border-zinc-700'
      }`}
    >
      <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-3 transition-colors ${isDragging ? 'bg-blue-500/20' : 'bg-zinc-800'}`}>
        <FolderOpen className={`w-6 h-6 ${isDragging ? 'text-blue-400' : 'text-zinc-500'}`} />
      </div>
      <p className="text-sm font-semibold text-zinc-300 mb-1">
        {isDragging ? 'Drop to analyze' : 'Drop file here'}
      </p>
      <p className="text-xs text-zinc-500 mb-5 text-center">PDF, DOCX, XLSX, CSV supported</p>
      <label className="cursor-pointer bg-blue-600 hover:bg-blue-500 text-white font-semibold text-xs px-5 py-2.5 rounded-lg transition-colors flex items-center gap-2">
        <Upload className="w-3.5 h-3.5" />
        Browse File
        <input
          type="file"
          onChange={e => { const f = e.target.files?.[0]; if (f) onFile(f); }}
          className="hidden"
          accept=".pdf,.docx,.xlsx,.csv,.txt"
        />
      </label>
    </div>
  );
}

export default function DocumentIntelPage() {
  const documents = useLiveQuery(() => db.documents.orderBy('uploadedAt').reverse().toArray()) ?? [];
  const { addDocument, deleteDocument } = useDocumentStore();

  const [activeFile, setActiveFile] = useState<string>('');
  const [extracting, setExtracting] = useState(false);
  const [extracted, setExtracted] = useState<ExtractedData | null>(null);
  const [exportSuccess, setExportSuccess] = useState<string | null>(null);

  const processFile = async (file: File) => {
    setActiveFile(file.name);
    setExtracted(null);
    setExtracting(true);

    await addDocument({
      fileName: file.name,
      fileUrl: '#',
      fileType: file.name.split('.').pop() ?? 'unknown',
    });

    setTimeout(() => {
      setExtracting(false);
      setExtracted(detectExtractionType(file.name));
    }, 1800);
  };

  const handleExport = (format: 'txt' | 'html' | 'json') => {
    if (!extracted || !activeFile) return;
    if (format === 'txt') exportAsText(activeFile, extracted);
    if (format === 'html') exportAsHTML(activeFile, extracted);
    if (format === 'json') exportAsJSON(activeFile, extracted);
    setExportSuccess(format.toUpperCase());
    setTimeout(() => setExportSuccess(null), 3000);
  };

  const handleDelete = async (id: number | undefined) => {
    if (id === undefined) return;
    await deleteDocument(id);
  };

  return (
    <div className="page flex flex-col gap-6 animate-fade-in">
      {/* Header */}
      <div className="page-header">
        <h1 className="text-2xl font-bold text-zinc-100 flex items-center gap-2">
          <FileText className="w-6 h-6 text-blue-500" />
          Document Intelligence Center
        </h1>
        <p className="text-sm text-zinc-400 mt-0.5">
          Upload technical specs, POs, or exam notifications to auto-extract tasks, risks, and action items.
        </p>
      </div>

      {/* Export success toast */}
      {exportSuccess && (
        <div className="fixed bottom-6 right-6 z-50 flex items-center gap-3 bg-emerald-900/90 border border-emerald-500/30 text-emerald-300 text-sm font-semibold px-4 py-3 rounded-xl shadow-xl animate-fade-in">
          <CheckCircle className="w-4 h-4" />
          Exported as {exportSuccess} successfully
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Panel */}
        <div className="flex flex-col gap-6">
          {/* Upload zone */}
          <Card header={<span className="text-zinc-200 font-semibold flex items-center gap-2"><Upload className="w-4 h-4 text-blue-400" /> Upload & Analyze</span>}>
            <DropZone onFile={processFile} />
            {activeFile && (
              <div className="mt-4 p-3 border border-blue-500/20 rounded-lg bg-blue-500/5 flex items-center justify-between gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  <FileText className="w-4 h-4 text-blue-400 flex-shrink-0" />
                  <span className="text-xs text-zinc-300 truncate">{activeFile}</span>
                </div>
                {extracting
                  ? <Loader2 className="w-3.5 h-3.5 text-blue-400 animate-spin flex-shrink-0" />
                  : <CheckCircle className="w-3.5 h-3.5 text-emerald-400 flex-shrink-0" />
                }
              </div>
            )}
          </Card>

          {/* Document Library */}
          <Card header={
            <span className="text-zinc-200 font-semibold flex items-center gap-2">
              <HardDrive className="w-4 h-4 text-zinc-500" />
              Indexed Library
              <span className="ml-auto text-[10px] text-zinc-500 font-mono">{documents.length} files</span>
            </span>
          }>
            <div className="flex flex-col gap-2 max-h-72 overflow-y-auto">
              {documents.length === 0 ? (
                <div className="text-center py-6 text-zinc-600 text-xs">No files indexed yet.</div>
              ) : (
                documents.map(doc => (
                  <div
                    key={doc.id}
                    className={`flex justify-between items-center p-2.5 border rounded-lg text-xs cursor-pointer transition-colors ${
                      activeFile === doc.fileName
                        ? 'border-blue-500/30 bg-blue-500/5'
                        : 'border-zinc-850 bg-zinc-950/40 hover:border-zinc-700'
                    }`}
                    onClick={() => {
                      setActiveFile(doc.fileName);
                      setExtracted(detectExtractionType(doc.fileName));
                    }}
                  >
                    <div className="flex items-center gap-2 overflow-hidden mr-2">
                      <FileText className="w-4 h-4 text-blue-400 flex-shrink-0" />
                      <div className="truncate">
                        <div className="text-zinc-200 truncate font-medium">{doc.fileName}</div>
                        <div className="text-[10px] text-zinc-600 uppercase font-mono">
                          {doc.fileType} · {new Date(doc.uploadedAt).toLocaleDateString('en-IN')}
                        </div>
                      </div>
                    </div>
                    <button
                      onClick={e => { e.stopPropagation(); handleDelete(doc.id); }}
                      className="text-zinc-600 hover:text-rose-400 p-1 rounded transition-colors"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))
              )}
            </div>
          </Card>

          {/* Export Actions — shown only when data is ready */}
          {extracted && (
            <Card header={<span className="text-zinc-200 font-semibold flex items-center gap-2"><FileDown className="w-4 h-4 text-emerald-400" /> Export Report</span>}>
              <div className="flex flex-col gap-2">
                <p className="text-[10px] text-zinc-500 mb-1">Download extracted intelligence in your preferred format.</p>
                {[
                  { fmt: 'txt' as const, label: 'Plain Text (.txt)', icon: FileText, desc: 'Simple readable format' },
                  { fmt: 'html' as const, label: 'HTML Report (.html)', icon: FileCode, desc: 'Styled, shareable report' },
                  { fmt: 'json' as const, label: 'Structured JSON (.json)', icon: FileDown, desc: 'Machine-readable data' },
                ].map(({ fmt, label, icon: Icon, desc }) => (
                  <button
                    key={fmt}
                    onClick={() => handleExport(fmt)}
                    className="flex items-center gap-3 p-3 border border-zinc-800 rounded-lg hover:border-zinc-700 hover:bg-zinc-900/30 transition-all text-left group"
                  >
                    <div className="w-8 h-8 rounded-lg bg-zinc-800 flex items-center justify-center flex-shrink-0">
                      <Icon className="w-4 h-4 text-emerald-400" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-xs font-semibold text-zinc-200">{label}</div>
                      <div className="text-[10px] text-zinc-500">{desc}</div>
                    </div>
                    <Download className="w-3.5 h-3.5 text-zinc-600 group-hover:text-emerald-400 transition-colors" />
                  </button>
                ))}
              </div>
            </Card>
          )}
        </div>

        {/* Right Panel — Extraction Results */}
        <div className="lg:col-span-2 flex flex-col gap-6">
          {extracting ? (
            <Card header={null}>
              <div className="flex flex-col items-center justify-center py-20 gap-5">
                <div className="relative">
                  <div className="w-14 h-14 rounded-full border-4 border-zinc-800" />
                  <div className="absolute inset-0 w-14 h-14 rounded-full border-4 border-blue-500 border-t-transparent animate-spin" />
                </div>
                <div className="text-center">
                  <p className="text-sm font-semibold text-zinc-300">Extracting intelligence...</p>
                  <p className="text-xs text-zinc-500 mt-1">Parsing entities, tasks, deadlines & risks</p>
                </div>
              </div>
            </Card>
          ) : extracted ? (
            <>
              {/* Summary */}
              <Card header={
                <span className="text-zinc-200 font-semibold flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-blue-400" />
                  Intelligence Report
                  <span className="ml-auto text-[10px] font-mono text-zinc-500 truncate max-w-[150px]">{activeFile}</span>
                </span>
              }>
                <div className="flex flex-col gap-5 text-xs">
                  {/* Executive summary */}
                  <div>
                    <span className="text-[10px] uppercase font-bold text-zinc-500 block mb-2">Executive Summary</span>
                    <p className="leading-relaxed text-zinc-300 bg-zinc-900/30 p-3.5 rounded-xl border border-zinc-800">
                      {extracted.summary}
                    </p>
                  </div>

                  {/* 2-col grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Tasks */}
                    <IntelSection
                      title="Action Items"
                      icon={<CheckCircle className="w-3.5 h-3.5 text-emerald-400" />}
                      items={extracted.tasks}
                      itemColor="text-zinc-300"
                      borderColor="border-emerald-500/20"
                      bg="bg-emerald-500/5"
                    />
                    {/* Deadlines */}
                    <IntelSection
                      title="Deadlines"
                      icon={<Calendar className="w-3.5 h-3.5 text-amber-400" />}
                      items={extracted.deadlines}
                      itemColor="text-zinc-300"
                      borderColor="border-amber-500/20"
                      bg="bg-amber-500/5"
                    />
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Opportunities */}
                    <IntelSection
                      title="Opportunities"
                      icon={<Sparkles className="w-3.5 h-3.5 text-cyan-400" />}
                      items={extracted.opportunities}
                      itemColor="text-zinc-300"
                      borderColor="border-cyan-500/20"
                      bg="bg-cyan-500/5"
                    />
                    {/* Risks */}
                    <IntelSection
                      title="Risk Signals"
                      icon={<AlertTriangle className="w-3.5 h-3.5 text-rose-400" />}
                      items={extracted.risks}
                      itemColor="text-zinc-300"
                      borderColor="border-rose-500/20"
                      bg="bg-rose-500/5"
                    />
                  </div>

                  {/* Contacts */}
                  <IntelSection
                    title="Contacts Identified"
                    icon={<User className="w-3.5 h-3.5 text-violet-400" />}
                    items={extracted.contacts}
                    itemColor="text-zinc-300"
                    borderColor="border-violet-500/20"
                    bg="bg-violet-500/5"
                  />

                  {/* Quick Actions */}
                  <div className="flex flex-wrap gap-2 border-t border-zinc-800 pt-4">
                    <span className="text-[10px] text-zinc-500 self-center">Quick export:</span>
                    {(['txt', 'html', 'json'] as const).map(fmt => (
                      <button
                        key={fmt}
                        onClick={() => handleExport(fmt)}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-900 hover:bg-zinc-800 border border-zinc-700 hover:border-zinc-600 rounded-lg text-[10px] font-semibold text-zinc-300 transition-colors uppercase"
                      >
                        <Download className="w-3 h-3" />
                        {fmt}
                      </button>
                    ))}
                  </div>
                </div>
              </Card>
            </>
          ) : (
            <Card header={null}>
              <div className="flex flex-col items-center justify-center py-20 gap-4 text-center">
                <div className="w-16 h-16 rounded-2xl bg-zinc-900 border border-zinc-800 flex items-center justify-center">
                  <FileText className="w-8 h-8 text-zinc-700" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-zinc-400">No document loaded</p>
                  <p className="text-xs text-zinc-600 mt-1">Upload a file or select from the library to extract intelligence.</p>
                </div>
              </div>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}

function IntelSection({
  title,
  icon,
  items,
  itemColor,
  borderColor,
  bg,
}: {
  title: string;
  icon: React.ReactNode;
  items: string[];
  itemColor: string;
  borderColor: string;
  bg: string;
}) {
  return (
    <div className={`p-3.5 border rounded-xl ${borderColor} ${bg}`}>
      <span className="text-[10px] uppercase font-bold text-zinc-500 flex items-center gap-1.5 mb-2.5">
        {icon}
        {title}
        <span className="ml-auto text-zinc-600">{items.length}</span>
      </span>
      {items.length === 0 ? (
        <p className="text-[10px] text-zinc-600 italic">None identified.</p>
      ) : (
        <ul className="flex flex-col gap-2">
          {items.map((item, i) => (
            <li key={i} className={`flex items-start gap-2 ${itemColor} text-[11px] leading-relaxed`}>
              <ArrowRight className="w-3 h-3 text-zinc-600 flex-shrink-0 mt-0.5" />
              {item}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
